# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Rishabh Dwivedi (rishabhdwivedi17@gmail.com)

[package]
name = "rs-paint"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
